# This file is a template, and might need editing before it works on your project.
# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/ee/pages/
stages:
  - build
  - deploy

build:
  stage: build
  # Use Ruby Docker image
  image: ruby:2.6 
  variables:
    JEKYLL_ENV: production
    LC_ALL: C.UTF-8
  before_script:
    - git clone https://gitlab.cern.ch/jmontejo/jekyll-theme-jmontejo.git jekyll-theme-jmontejo
    - cd jekyll-theme-jmontejo 
    - rm -rf .git* .travis.yml README.md LICENSE.txt 
    - cd ../
    - mv -vn jekyll-theme-jmontejo/* .
    - rm -rf jekyll-theme-jmontejo
    - gem install bundler
    - bundle install
  script: # Generate public site and deploy
    - bundle exec jekyll build -d public --trace
  artifacts: # Save a zipped version for download
    paths:
      - public

deploy:
  stage: deploy
  variables:
    "EOS_PATH": "/eos/user/j/jmontejo/www/students"
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer
  script:
    - deploy-eos
  #only: # Only deploy the master branch
  #  - master

